name: Deploy Bicep Infrastructure

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'bicep/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'bicep/**'
      - '.github/workflows/deploy.yml'

env:
  AZURE_SUBSCRIPTION_ID: f87077b9-ed2e-497d-876f-02c0a33e3774
  RESOURCE_GROUP_NAME: RGAUANSDeploy
  LOCATION: australiaeast
  KEY_VAULT_NAME: kvaueansdeploy
  VM_NAME: vmauansvm01

jobs:
  validate:
    name: Validate Bicep Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Azure CLI
        uses: azure/setup-azure-cli@v3

      - name: Install Bicep CLI
        run: |
          az bicep install
          az bicep version

      - name: Validate Key Vault Bicep
        run: |
          echo "Validating Key Vault Bicep template..."
          az bicep build --file bicep/keyvault.bicep --outfile keyvault.json
          echo "Key Vault Bicep validation successful"

      - name: Validate VM Bicep
        run: |
          echo "Validating VM Bicep template..."
          az bicep build --file bicep/main.bicep --outfile main.json
          echo "VM Bicep validation successful"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bicep-templates
          path: |
            keyvault.json
            main.json

  test:
    name: Test Deployment with What-If
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: What-If Key Vault
        run: |
          echo "Running What-If for Key Vault deployment..."
          az deployment group what-if \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --template-file bicep/keyvault.bicep \
            --parameters bicep/keyvault.bicepparam \
            --name 'WhatIfKeyVault'

      - name: What-If VM
        run: |
          echo "Running What-If for VM deployment..."
          az deployment group what-if \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --template-file bicep/main.bicep \
            --parameters bicep/main.bicepparam \
            --name 'WhatIfVM'

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: Production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Key Vault
        run: |
          echo "Deploying Key Vault..."
          PRINCIPAL_ID=$(az ad signed-in-user show --query id -o tsv)
          
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --template-file bicep/keyvault.bicep \
            --parameters bicep/keyvault.bicepparam \
            --parameters principalId=$PRINCIPAL_ID \
            --name 'DeployKeyVault-${{ github.run_id }}'

      - name: Deploy Virtual Machine
        run: |
          echo "Deploying Virtual Machine..."
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --template-file bicep/main.bicep \
            --parameters bicep/main.bicepparam \
            --name 'DeployVM-${{ github.run_id }}'

  validate-deployment:
    name: Validate Deployment
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Resources
        run: |
          echo "Verifying deployed resources..."
          
          echo "Checking Key Vault..."
          az keyvault show --name ${{ env.KEY_VAULT_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}
          
          echo "Checking Virtual Machine..."
          az vm show --name ${{ env.VM_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}
          
          echo "Getting VM connection details..."
          VM_IP=$(az vm show -d --name ${{ env.VM_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} --query publicIps -o tsv)
          echo "VM Public IP: $VM_IP"

      - name: Generate Deployment Report
        run: |
          echo "=== Deployment Summary ===" > deployment-report.txt
          echo "Deployment Date: $(date)" >> deployment-report.txt
          echo "Resource Group: ${{ env.RESOURCE_GROUP_NAME }}" >> deployment-report.txt
          echo "Location: ${{ env.LOCATION }}" >> deployment-report.txt
          echo "VM Name: ${{ env.VM_NAME }}" >> deployment-report.txt
          echo "Key Vault Name: ${{ env.KEY_VAULT_NAME }}" >> deployment-report.txt
          echo "" >> deployment-report.txt
          echo "=== VM Details ===" >> deployment-report.txt
          az vm show -d --name ${{ env.VM_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} >> deployment-report.txt
          
          cat deployment-report.txt

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: deployment-report
          path: deployment-report.txt
